---
- hosts: localhost
  remote_user: root

  tasks:
  - name:
    user:
      name: schaary
      password: $6$OQesvdeVn2$ZrhLTvHBo0TDBIiX/h0BbYX4ob5kfq7ONy6/UfM1sBg9RYkqwtT.aindSRZLCYhqKZIYTeMvRk9R6SHJfFUll.
      groups: # Empty by default, here we give it some groups
      #       - docker
      # - sudo
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      system: no             # Defaults to no
      createhome: yes        # Defaults to yes
      home: /home/schaary    # Defaults to /home/<username>
